name: Bug Report
description: Report a bug to help us improve
body:
  - type: markdown
    attributes:
      value: |
        ### Before reporting
        - [ ] Searched existing issues
        - [ ] Checked documentation
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Clear and concise description of the bug
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Screenshots, logs, environment details, etc.
  - type: input
    id: version
    attributes:
      label: Version
      description: MUTS version or commit SHA
      placeholder: 1.0.0 or abc1234
